### PR TITLE
Sortable table plugin

### PR DESCRIPTION
**Pull request by zarino**
For #96.

Add a class to a table, and it becomes sortable!

Works with [fixed headers](https://github.com/mysociety/popolo-viewer-sinatra/commit/472768fa5acb06b9c3b983d63a07ded428f87505) too.

sortable

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
Woohoo! :rocket:

**Comment by tmtmtmtm** [comment]
Erk. This breaks quite badly for Finland.

**Comment by tmtmtmtm** [comment]
I'm assuming it's to do with the rowspans...

**Comment by zarino** [comment]
Oh no! Rowspans!

I guess, the first time you sort the table, it's going to have to un-span the double-height cells (and duplicate their content into all the now missing cells below) so the rows can be sorted independently. Unfortunately, it means, once you return back to the original (unsorted) order, the rowspans will have gone. But at least all the data will be there. Would you be happy with that @tmtmtmtm?

**Comment by tmtmtmtm** [comment]
Perhaps then that should be the default position? i.e. have the generated table always show full rows by default (no spans). Then we have a JS-function that can do the combining if the table is sorted by name, and consecutive rows are the same person (there's already a `mem-{id}` set on the row). Then we just trigger that on initial load, or when sorting by name, and detrigger it before any other sort?

(BTW: I've pushed a hotfix to disable it just for Finland on the live site)

**Pull request merged**
